Center-for-AI-Innovation/ai-ta-backend

- ai_ta_backend/main.py
- ai_ta_backend/vector_database.py
Clones the GitHub repo and uploads to QDRANT.
> GitHub Ingest

- ai_ta_backend/vector_database.py
1. Added .md to to `_ingest_single_txt()`
2. Modified `_ingest_single_py()` - PythonLoader() had some issue, so now storing and deleting python files instead of using tmp files
> Testing .txt and .py ingest functions

- ai_ta_backend/vector_database.py
Make all necessary adjustments to make our 'metadata' dict, a top-level object for search Index compatibility
> Qdrant schema overhaul -- add Search Index on `course_name` for latency speedup

- ai_ta_backend/nomic_logging.py
Modified error handling - now we create new maps only if we get a very specific error. For the rest, we return "Logging failed".
> Nomic Error Handling

- ai_ta_backend/export_data.py
- ai_ta_backend/main.py
- ai_ta_backend/vector_database.py
- requirements.txt
API endpoint for exporting conversation history as a CSV file.
> Export conversation history

- ai_ta_backend/filtering_contexts.py
- ai_ta_backend/main.py
- ai_ta_backend/vector_database.py
The only part NOT fixed is /webscrape, which COULD have more problems. But we're deprecating that very soon, hopefully be end of next week.
> Fix Dangling Threads

- ai_ta_backend/main.py
- ai_ta_backend/vector_database.py
Supporting: https://github.com/KastanDay/ai-ta-frontend/pull/95
> Add Backend support for new Crawlee ingest on Frontend

- ai_ta_backend/emails.py
- ai_ta_backend/export_data.py
- ai_ta_backend/main.py
Moving Kastan's email from main receipients to bcc receipients.
> BCC receipients in email

- ai_ta_backend/nomic_logging.py
Function got messed up during initial document map merge. Trying to fix.
> Nomic Conversation Log Fix

- ai_ta_backend/database/sql.py
- ai_ta_backend/service/export_service.py
Background export was not being initiated due to pickling error - moved the function outside the ExportService class.
> Async Export Fix

- ai_ta_backend/database/vector.py
Add condition to match documents with specified doc_groups or where doc_groups is not set
> Filtering documents where no document groups are set

- ai_ta_backend/beam/ingest.py
- ai_ta_backend/beam/nomic_logging.py
- ai_ta_backend/service/nomic_service.py
Identified and fixed IndexError and AssertionError
Observed multiple document maps being created for the same course - need to investigate
> Fix for Nomic errors seen since last merge

- ai_ta_backend/main.py
- ai_ta_backend/service/export_service.py
API endpoint: /export-conversations-custom
Parameters: 
course_name, from_date (optional), to_date (optional), destination_emails_list (comma separated strings)
UPDATE: switched this to GET
> New endpoint for conversation export which takes in emails list

- ai_ta_backend/beam/crop_tool.py
Valid inputs. Waiting on Vardhan for additional input validation rules and better parameter names for GPT to use.
```json
{
"base": 50,
"placebox": 9,
"areabox": "llc",
"date": "01/01",
"plap": "Springfield"
}
```
> Working crop tool, called by N8N. Nice!

- ai_ta_backend/beam/ingest.py
- ai_ta_backend/main.py
- ai_ta_backend/service/retrieval_service.py
Commenting Nomic from ingest and logging functions
> Nomic removal

- ai_ta_backend/beam/canvas_ingest.py
- ai_ta_backend/beam/ingest.py
Modifying the download functions to handle cases where "Files" and "Pages" section on Canvas are disabled for students.
> Fixing Canvas Ingest bugs

- ai_ta_backend/beam/canvas_ingest.py
Fixed pagination bug in module download
To-do:
> Canvas Fixes

- ai_ta_backend/database/sql.py
- ai_ta_backend/main.py
- ai_ta_backend/service/retrieval_service.py
- Added pagination for retrieving chat conversations
- Removed the getConversationHeatmapByHour endpoint and integrated that functionality into getConversationStats
- Fixed endless call bug
- Added getProjectStats 
- Created a project_stats table
- Created 2 triggers: project_stats_trigger  and after_project_insert
> Implement Pagination

- ai_ta_backend/main.py
- ai_ta_backend/service/nomic_service.py
- ai_ta_backend/utils/pubmed_extraction.py
Move PubMed into its own class so the ENV vars don't mess up people who don't want to use that functionality
> Hopefully fix nomic and minio

- ai_ta_backend/service/nomic_service.py
> Nomic Hot Fix 2

- ai_ta_backend/database/graph.py
- ai_ta_backend/main.py
- requirements.txt
I have created two endpoints `/getClinicalKGContexts` and `/getPrimeKGContexts` that are exposed through N8N tools. 
This can be tested locally by starting the development server:
`infisical run --watch --env=dev -- flask --app ai_ta_backend.main:app run --port 8000`
And running a curl request:
```bash
curl -G "http://localhost:8000/getClinicalKGContexts" \
-H "accept: application/json,text/html,application/xhtml+xml,application/xml,text/*;q=0.9, image/*;q=0.8, */*;q=0.7" \
--data-urlencode "user_query=What autosomal diseases result in immunodeficiency " \   
-L
```
<details><summary>Result</summary>
<p>
```json
{
"kg_result": [
{
"d.id": "DOID:0060023",
"d.name": "immunodeficiency with hyper IgM type 3"
},
{
"d.id": "DOID:0060023",
"d.name": "immunodeficiency with hyper IgM type 3"
},
{ …
```
> Knowledge Graph Retrieval Tool

- ai_ta_backend/rabbitmq/ingest.py
Worker was not logging these in postgres before.
> Move failed documents into Failed list
